### ISSUE TITLE
Support PEP660 (`pip install --editable`)

### ISSUE THREAD

**Issue by LecrisUT** [scikit-build/scikit-build-core#171] opened 2023-01-15 15:54 UTC
It might be enough to just wrap `build_editable` to `setuptools` one.

Just to make sure this works we should check that:
- a) Changing the python file should be reflected in the execution
- b) Updating on change of C source is outside of the scope of editable installs
- c) C built module libraries, etc. are installed in the correct python source folder. Maybe this can be exposed to user on CMake side so that they can be hooked correctly

**Comment by henryiii** [comment] 2023-01-19 16:56
Duplicate of #114. There are several things needed. Though a) yes, I think we can do that, b) We should be able to do this too (see meson-python's support) - though it would likely be under a configuration option), and c) a bit tricky, we can either try to put everything in source or have a custom loader - the latter unfortunately doesn't produce the right paths for coverage and such tools.

We really need #164 first, though. Users will expect an editable install to not rebuild everything every time.

Also, I'm prioritizing the PEP 517 mode (no setupools). With the setuptools module, maybe we can wrap `build_editiable`, I'm not sure. That also just might not be supported, with users requested to use the native support if they want editable installs. :)

**Comment by LecrisUT** [comment] 2023-01-19 17:11
I think it is worth shipping out these features gradually:
1. A simpler wrapper around an existing `build_editable` (e.g. `setuptools`) that does not do b) or c) yet, just allows the project to be installed via `pip install -e` and symlinks the python code. The dev would be responsible to do b) and c) manually
2. Implement c) within python. Preferably it should not be dependent on cmake because some devs might have a `pip` independent dev build that does not call `scikit-build-core`. This would mostly simplify the initial setup
3. Go beyond and make it interact with cmake for b)

The key is that even with the simple `setuptools` wrapper, it is already more convenient for developers to debug.

**Closed** 2023-04-12 09:41 UTC
